name=LcdI2C
version=1.0.0
author=Erick
maintainer=Erick
sentence=Libreria propia para LCD HD44780 (16x2, 20x4) con PCF8574/PCF8574A.
paragraph=Mapeo P0=RS, P1=RW, P2=E, P3=BL, P4-P7=D4-D7.
category=Display
url=
architectures=avr
